import './globals.css'
import type { Metadata } from 'next'
import { Toaster } from 'react-hot-toast'
import { Poppins } from 'next/font/google'
import Headers from './components/Headers'

const inter = Poppins({
  weight: '300',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className="overflow-x-hidden scrollbar scrollbar-w-2 scrollbar-thumb-sky-600  scrollbar-track-gray-200"
    >
      <body className={inter.className}>
          <Headers></Headers>
          {children}
        <Toaster />
      </body>
    </html>
  )
}
